service: "mini-movie-db"

provider:
  name: "aws"
  runtime: "nodejs8.10"
  region: "us-west-2"
  stage: ${opt:stage, "dev"}
  environment:
    stage: ${self:provider.stage}
    SENTRY_FILTER_LOCAL: false
    S3_BUCKET: ${self:service}-image-storage
    S3_HOST: "localhost"
    S3_PORT: 8000

plugins:
  - "serverless-sentry"
  - "serverless-s3-local"
  - "serverless-webpack"
  - "serverless-offline"
  - "serverless-plugin-scripts"

package:
  exclude:
    - "./ node_modules/**"
    - "./.eslintrc.json"
    - "./webpack.config.js"

custom:
  serverless-offline:
    port: 7331
  config:
    CACHE_INSTANCE_SIZE: "cache.t2.micro"
  sentry:
    dsn: ${env:SENTRY_DSN, ""}
    environment: ${opt:stage, self:provider.stage}
    organization: "saerisio"
    project: ${self:service}
    authToken: ${env:SENTRY_AUTH_TOKEN, ""}
    release:
      version: "codesandbox"
    filterLocal: false
    webpack:
      includeModules: true
      webpackConfig: "webpack.config.js"
  s3:
    host: ${self:provider.environment.S3_HOST}
    port: ${self:provider.environment.S3_PORT}
    directory: ./public

functions:
  graphql:
    handler: "src/index.graphqlHandler"
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
